version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=notify_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  notification-service:
    build: ./services/notification-service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=notify_db
      - DB_USER=postgres
      - DB_PASSWORD=your_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis

  user-service:
    build: ./services/user-service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=notify_db
      - DB_USER=postgres
      - DB_PASSWORD=your_password
    ports:
      - "5001:5001"
    depends_on:
      - postgres

  email-worker:
    build: ./services/email-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  audit-service:
    build: ./services/audit-service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=notify_db
      - DB_USER=postgres
      - DB_PASSWORD=your_password
    ports:
      - "5002:5002"
    depends_on:
      - postgres

  api-gateway:
    build: ./services/api-gateway
    environment:
      - NOTIFICATION_SERVICE_URL=http://notification-service:5000
      - USER_SERVICE_URL=http://user-service:5001
      - AUDIT_SERVICE_URL=http://audit-service:5002
    ports:
      - "8080:8080"
    depends_on:
      - notification-service
      - user-service
      - audit-service

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

volumes:
  postgres_data:
  redis_data:
